---
stages:
  - lint
  - release
  - build
  - deploy

workflow:
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_MESSAGE =~ /^chore\(release\):.*/'
      when: never
    - if: "'int' == $CI_COMMIT_BRANCH"
      variables:
        NEXT_URL: https://int.gnaumann.de
    - when: always

variables:
  NEXT_URL: https://gnaumann.de

.node-template:
  image: node:20-alpine3.18
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
  before_script:
    - npm i

next-lint:
  stage: lint
  extends: .node-template
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - npm run lint

release:
  stage: release
  image: quay.io/genaumann/pub/semantic-release:22.0.8
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
  artifacts:
    paths:
      - VERSION
      - package.json
      - package-lock.json
  script:
    - semantic-release

next-build:
  stage: build
  extends: .node-template
  tags:
    - gna
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
      needs:
        - job: release
          artifacts: true
    - if: "'int' == $CI_COMMIT_BRANCH"
  artifacts:
    expire_in: 2h
    paths:
      - .next
      - public
  script:
    - echo "Building image for ${NEXT_URL}"
    - apk add git
    - npm run build

container-build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.13.0-debug
    entrypoint: ['']
  tags:
    - gna
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH
      needs:
        - job: next-build
          artifacts: true
        - job: release
          artifacts: true
      variables:
        CONTAINER_TAG: latest
    - if: "'int' == $CI_COMMIT_BRANCH"
      needs:
        - job: next-build
          artifacts: true
      variables:
        VERSION: int-$CI_PIPELINE_ID
        CONTAINER_TAG: int
  before_script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - if [ ! "$VERSION" ] ; then VERSION=$(cat VERSION) ; else VERSION=$VERSION ; fi
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --build-arg "NEXT_URL=${NEXT_URL}"
      --dockerfile "${CI_PROJECT_DIR}/Containerfile"
      --destination "${CI_REGISTRY}/genaumann/gnaumann.de:${VERSION}"
      --destination "${CI_REGISTRY}/genaumann/gnaumann.de:${CONTAINER_TAG}"

salt-deploy:
  stage: deploy
  image: quay.io/genaumann/pub/saltleapi:1.1.4
  tags:
    - gna
  environment:
    name: $DEPLOY_ENV
    url: $NEXT_URL
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      needs:
        - job: container-build
          artifacts: false
        - job: release
          artifacts: true
      variables:
        DEPLOY_ENV: production
        CONTAINER_NAME: gnaumann
    - if: "'int' == $CI_COMMIT_BRANCH"
      needs:
        - job: container-build
          artifacts: false
      variables:
        DEPLOY_ENV: integration
        CONTAINER_NAME: gnaumann-int
        VERSION: int-$CI_PIPELINE_ID
  script:
    - if [ ! "$VERSION" ] ; then VERSION=$(cat VERSION) ; else VERSION=$VERSION ; fi
    - saltleapi hook.nauminet.de state.apply -a api.gnaumann-web -k pillar="{\"docker\":{\"containers\":{\"${CONTAINER_NAME}\":{\"image\":\"${CI_REGISTRY}/genaumann/gnaumann.de:${VERSION}\"}}}}"
